### ISSUE TITLE
What's different between this plugin and maven-compiler-plugin?

### ISSUE THREAD

**Issue by vipcxj** [bsorrentino/maven-annotation-plugin#97]
I means maven-compiler-plugin also support annotation processor, what problem this plugin solve?
Recently I am develop an annotation processor. With maven tool-chains on, my annotation processor can not print anything to the console. I try a logger system such as log4j2, and use a file appender, but the file is empty. So I want to find a better maven plugin to support annotation processor.

**Comment by bsorrentino** [comment]
Hi @vipcxj 

Great question 👍

Firstly, this plugin was born before official support of **JSR 269** from **maven compiler plugin** and as alter ego of [apt-maven-plugin](https://search.maven.org/artifact/org.codehaus.mojo/apt-maven-plugin/1.0-alpha-5/maven-plugin) 

I've used such plugin in a lot of projects and it is become quite famous in OSS community so I received new proposal, issues and PR that have push me to continue to maintain and evolve

Really I haven't a detailed answer to your question however I can say that I added some features based on needs and feedbacks like for example: [processSourceArtifacts](http://bsorrentino.github.io/maven-annotation-plugin/process-mojo.html#processSourceArtifacts) and [appendSourceArtifacts](http://bsorrentino.github.io/maven-annotation-plugin/process-mojo.html#appendSourceArtifacts) specifically developed to allow processor to easily access to sources rather than classes.

In this project there are also some utilities classes that could help you to develop your Annotation Processor
